### ISSUE TITLE
RDF - Turtle based configuration

### ISSUE THREAD

**Issue by igrangel** [i40-Tools/AMLGoldStandardGenerator#5]
This is wrong: aml:hasHeterogeneity "M1,M2";
The heterogeneities are resources, not literals. Would be something like this 
m1 a aml:Heterogeneity ;
m1 schema:name "Data types"@en;
Then, you connect in this way: 
aml:seed-1
     aml:hasHeterogeneity m1 , m2 ;
.
Also, you can't say that aml:seed1 is of rdf:type aml:Heterogeneity . 
There are 2 types of things, aml files which are the input of our method and the heterogeneities that we are applying to the seeds.

**Comment by omarrana** [comment]
was the previous iteration ok ? it was easy to understand but  i just changed it due to we have to write similar data in RDF a lot of time to define another heterogeneity for the same seed.

@prefix aml:  http://iais.fraunhofer.de/aml# .
@prefix rdf:  http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix rdfs:  http://www.w3.org/2000/01/rdf-schema# .
@prefix ebucore:  http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#.

aml:Granularity
     aml:hasName "Granulariy";
     aml:hasID   "M2";
     aml:hasInputPath   "D://...";
     aml:hasOutputPath  "D://...";
     ebucore:filename   "Granularity.aml";
     rdf:type           aml:Heterogeneity .

aml:schema
     aml:hasName "schema";
     aml:hasID   "M3";
     aml:hasInputPath   "D://...";
     aml:hasOutputPath  "D://...";
     ebucore:filename   "schema.aml";
     rdf:type           aml:Heterogeneity .

i will come up with a new version and post it.

**Comment by igrangel** [comment]
Please, draw a diagram of the classes and relation of this? Like our basic ontology for describing the Heterogeneity problems.

**Comment by omarrana** [comment]
ok, as soon i finish precision and recall. ill make it.

**Comment by igrangel** [comment]
We don't need the Heterogeneities as Classes, but as instances. https://github.com/i40-Tools/AMLGoldStandardGenerator/commit/f7411da4e2f70374b3a792fcaf26125d85bc1244#diff-8242dc232304c206c9bef665778efd24R34. Please change them.
